(* Generated by tools/gen_opcodes.py from CPython 3.13.5 — DO NOT EDIT.
   Regenerate with: dune build @gen && dune promote *)

(** CPython opcodes, as a pure OCaml variant.

    Union of all real opcodes (numeric value < 256) of the supported CPython
    versions (currently: 3.13.5). Pseudo-opcodes never survive assembly and are
    excluded; specialized (adaptive) opcodes never appear in freshly compiled
    code.

    [@@deriving opcode] declares [to_string], [of_string], [all] (declaration
    order, i.e. alphabetical), and one predicate per flag attribute:
    - [has_arg]: [i.arg] is meaningful (HAVE_ARGUMENT).
    - [is_jump]: the arg is a jump target (in pytecode: an absolute instruction
      index).
    - [has_const]: the arg indexes [code.consts].
    - [has_name]: the arg indexes [code.names] (possibly with low flag bits,
      e.g. LOAD_GLOBAL/LOAD_ATTR).
    - [has_local]: the arg indexes [code.localsplus].
    - [has_free]: the arg indexes [code.localsplus] (cell/free slot).
    - [has_exc]: intrinsic exception-related opcode (dis.hasexc). *)

type t =
  | BEFORE_ASYNC_WITH
  | BEFORE_WITH
  | BINARY_OP
  | BINARY_SLICE
  | BINARY_SUBSCR
  | BUILD_CONST_KEY_MAP
  | BUILD_LIST
  | BUILD_MAP
  | BUILD_SET
  | BUILD_SLICE
  | BUILD_STRING
  | BUILD_TUPLE
  | CACHE
  | CALL
  | CALL_FUNCTION_EX
  | CALL_INTRINSIC_1
  | CALL_INTRINSIC_2
  | CALL_KW
  | CHECK_EG_MATCH
  | CHECK_EXC_MATCH
  | CLEANUP_THROW
  | COMPARE_OP
  | CONTAINS_OP
  | CONVERT_VALUE
  | COPY
  | COPY_FREE_VARS
  | DELETE_ATTR
  | DELETE_DEREF
  | DELETE_FAST
  | DELETE_GLOBAL
  | DELETE_NAME
  | DELETE_SUBSCR
  | DICT_MERGE
  | DICT_UPDATE
  | END_ASYNC_FOR
  | END_FOR
  | END_SEND
  | ENTER_EXECUTOR
  | EXIT_INIT_CHECK
  | EXTENDED_ARG
  | FORMAT_SIMPLE
  | FORMAT_WITH_SPEC
  | FOR_ITER
  | GET_AITER
  | GET_ANEXT
  | GET_AWAITABLE
  | GET_ITER
  | GET_LEN
  | GET_YIELD_FROM_ITER
  | IMPORT_FROM
  | IMPORT_NAME
  | INSTRUMENTED_CALL
  | INSTRUMENTED_CALL_FUNCTION_EX
  | INSTRUMENTED_CALL_KW
  | INSTRUMENTED_END_FOR
  | INSTRUMENTED_END_SEND
  | INSTRUMENTED_FOR_ITER
  | INSTRUMENTED_INSTRUCTION
  | INSTRUMENTED_JUMP_BACKWARD
  | INSTRUMENTED_JUMP_FORWARD
  | INSTRUMENTED_LINE
  | INSTRUMENTED_LOAD_SUPER_ATTR
  | INSTRUMENTED_POP_JUMP_IF_FALSE
  | INSTRUMENTED_POP_JUMP_IF_NONE
  | INSTRUMENTED_POP_JUMP_IF_NOT_NONE
  | INSTRUMENTED_POP_JUMP_IF_TRUE
  | INSTRUMENTED_RESUME
  | INSTRUMENTED_RETURN_CONST
  | INSTRUMENTED_RETURN_VALUE
  | INSTRUMENTED_YIELD_VALUE
  | INTERPRETER_EXIT
  | IS_OP
  | JUMP_BACKWARD
  | JUMP_BACKWARD_NO_INTERRUPT
  | JUMP_FORWARD
  | LIST_APPEND
  | LIST_EXTEND
  | LOAD_ASSERTION_ERROR
  | LOAD_ATTR
  | LOAD_BUILD_CLASS
  | LOAD_CONST
  | LOAD_DEREF
  | LOAD_FAST
  | LOAD_FAST_AND_CLEAR
  | LOAD_FAST_CHECK
  | LOAD_FAST_LOAD_FAST
  | LOAD_FROM_DICT_OR_DEREF
  | LOAD_FROM_DICT_OR_GLOBALS
  | LOAD_GLOBAL
  | LOAD_LOCALS
  | LOAD_NAME
  | LOAD_SUPER_ATTR
  | MAKE_CELL
  | MAKE_FUNCTION
  | MAP_ADD
  | MATCH_CLASS
  | MATCH_KEYS
  | MATCH_MAPPING
  | MATCH_SEQUENCE
  | NOP
  | POP_EXCEPT
  | POP_JUMP_IF_FALSE
  | POP_JUMP_IF_NONE
  | POP_JUMP_IF_NOT_NONE
  | POP_JUMP_IF_TRUE
  | POP_TOP
  | PUSH_EXC_INFO
  | PUSH_NULL
  | RAISE_VARARGS
  | RERAISE
  | RESERVED
  | RESUME
  | RETURN_CONST
  | RETURN_GENERATOR
  | RETURN_VALUE
  | SEND
  | SETUP_ANNOTATIONS
  | SET_ADD
  | SET_FUNCTION_ATTRIBUTE
  | SET_UPDATE
  | STORE_ATTR
  | STORE_DEREF
  | STORE_FAST
  | STORE_FAST_LOAD_FAST
  | STORE_FAST_STORE_FAST
  | STORE_GLOBAL
  | STORE_NAME
  | STORE_SLICE
  | STORE_SUBSCR
  | SWAP
  | TO_BOOL
  | UNARY_INVERT
  | UNARY_NEGATIVE
  | UNARY_NOT
  | UNPACK_EX
  | UNPACK_SEQUENCE
  | WITH_EXCEPT_START
  | YIELD_VALUE
[@@deriving opcode, eq, ord]

val hash : t -> int
val pp : Format.formatter -> t -> unit

val python_version : string
(** Full version of the CPython these tables were generated from. *)

val binary_op_repr : string array
(** BINARY_OP arg -> operator string (e.g. ["+"]); display only. *)

val cmp_op_repr : string array
(** COMPARE_OP (arg lsr 5) -> operator string; display only. *)
