(* Generated by tools/gen_opcodes.py from CPython 3.13.5 — DO NOT EDIT.
   Regenerate with: dune build @gen && dune promote *)

type t =
  | BEFORE_ASYNC_WITH
  | BEFORE_WITH
  | BINARY_OP [@has_arg]
  | BINARY_SLICE
  | BINARY_SUBSCR
  | BUILD_CONST_KEY_MAP [@has_arg]
  | BUILD_LIST [@has_arg]
  | BUILD_MAP [@has_arg]
  | BUILD_SET [@has_arg]
  | BUILD_SLICE [@has_arg]
  | BUILD_STRING [@has_arg]
  | BUILD_TUPLE [@has_arg]
  | CACHE
  | CALL [@has_arg]
  | CALL_FUNCTION_EX [@has_arg]
  | CALL_INTRINSIC_1 [@has_arg]
  | CALL_INTRINSIC_2 [@has_arg]
  | CALL_KW [@has_arg]
  | CHECK_EG_MATCH
  | CHECK_EXC_MATCH
  | CLEANUP_THROW
  | COMPARE_OP [@has_arg]
  | CONTAINS_OP [@has_arg]
  | CONVERT_VALUE [@has_arg]
  | COPY [@has_arg]
  | COPY_FREE_VARS [@has_arg]
  | DELETE_ATTR [@has_arg] [@has_name]
  | DELETE_DEREF [@has_arg] [@has_free]
  | DELETE_FAST [@has_arg] [@has_local]
  | DELETE_GLOBAL [@has_arg] [@has_name]
  | DELETE_NAME [@has_arg] [@has_name]
  | DELETE_SUBSCR
  | DICT_MERGE [@has_arg]
  | DICT_UPDATE [@has_arg]
  | END_ASYNC_FOR
  | END_FOR
  | END_SEND
  | ENTER_EXECUTOR [@has_arg]
  | EXIT_INIT_CHECK
  | EXTENDED_ARG [@has_arg]
  | FORMAT_SIMPLE
  | FORMAT_WITH_SPEC
  | FOR_ITER [@has_arg] [@is_jump]
  | GET_AITER
  | GET_ANEXT
  | GET_AWAITABLE [@has_arg]
  | GET_ITER
  | GET_LEN
  | GET_YIELD_FROM_ITER
  | IMPORT_FROM [@has_arg] [@has_name]
  | IMPORT_NAME [@has_arg] [@has_name]
  | INSTRUMENTED_CALL [@has_arg]
  | INSTRUMENTED_CALL_FUNCTION_EX
  | INSTRUMENTED_CALL_KW [@has_arg]
  | INSTRUMENTED_END_FOR
  | INSTRUMENTED_END_SEND
  | INSTRUMENTED_FOR_ITER [@has_arg]
  | INSTRUMENTED_INSTRUCTION
  | INSTRUMENTED_JUMP_BACKWARD [@has_arg]
  | INSTRUMENTED_JUMP_FORWARD [@has_arg]
  | INSTRUMENTED_LINE
  | INSTRUMENTED_LOAD_SUPER_ATTR [@has_arg]
  | INSTRUMENTED_POP_JUMP_IF_FALSE [@has_arg]
  | INSTRUMENTED_POP_JUMP_IF_NONE [@has_arg]
  | INSTRUMENTED_POP_JUMP_IF_NOT_NONE [@has_arg]
  | INSTRUMENTED_POP_JUMP_IF_TRUE [@has_arg]
  | INSTRUMENTED_RESUME [@has_arg]
  | INSTRUMENTED_RETURN_CONST [@has_arg] [@has_const]
  | INSTRUMENTED_RETURN_VALUE
  | INSTRUMENTED_YIELD_VALUE [@has_arg]
  | INTERPRETER_EXIT
  | IS_OP [@has_arg]
  | JUMP_BACKWARD [@has_arg] [@is_jump]
  | JUMP_BACKWARD_NO_INTERRUPT [@has_arg] [@is_jump]
  | JUMP_FORWARD [@has_arg] [@is_jump]
  | LIST_APPEND [@has_arg]
  | LIST_EXTEND [@has_arg]
  | LOAD_ASSERTION_ERROR
  | LOAD_ATTR [@has_arg] [@has_name]
  | LOAD_BUILD_CLASS
  | LOAD_CONST [@has_arg] [@has_const]
  | LOAD_DEREF [@has_arg] [@has_free]
  | LOAD_FAST [@has_arg] [@has_local]
  | LOAD_FAST_AND_CLEAR [@has_arg] [@has_local]
  | LOAD_FAST_CHECK [@has_arg] [@has_local]
  | LOAD_FAST_LOAD_FAST [@has_arg] [@has_local]
  | LOAD_FROM_DICT_OR_DEREF [@has_arg] [@has_free]
  | LOAD_FROM_DICT_OR_GLOBALS [@has_arg] [@has_name]
  | LOAD_GLOBAL [@has_arg] [@has_name]
  | LOAD_LOCALS
  | LOAD_NAME [@has_arg] [@has_name]
  | LOAD_SUPER_ATTR [@has_arg] [@has_name]
  | MAKE_CELL [@has_arg] [@has_free]
  | MAKE_FUNCTION
  | MAP_ADD [@has_arg]
  | MATCH_CLASS [@has_arg]
  | MATCH_KEYS
  | MATCH_MAPPING
  | MATCH_SEQUENCE
  | NOP
  | POP_EXCEPT
  | POP_JUMP_IF_FALSE [@has_arg] [@is_jump]
  | POP_JUMP_IF_NONE [@has_arg] [@is_jump]
  | POP_JUMP_IF_NOT_NONE [@has_arg] [@is_jump]
  | POP_JUMP_IF_TRUE [@has_arg] [@is_jump]
  | POP_TOP
  | PUSH_EXC_INFO
  | PUSH_NULL
  | RAISE_VARARGS [@has_arg]
  | RERAISE [@has_arg]
  | RESERVED
  | RESUME [@has_arg]
  | RETURN_CONST [@has_arg] [@has_const]
  | RETURN_GENERATOR
  | RETURN_VALUE
  | SEND [@has_arg] [@is_jump]
  | SETUP_ANNOTATIONS
  | SET_ADD [@has_arg]
  | SET_FUNCTION_ATTRIBUTE [@has_arg]
  | SET_UPDATE [@has_arg]
  | STORE_ATTR [@has_arg] [@has_name]
  | STORE_DEREF [@has_arg] [@has_free]
  | STORE_FAST [@has_arg] [@has_local]
  | STORE_FAST_LOAD_FAST [@has_arg] [@has_local]
  | STORE_FAST_STORE_FAST [@has_arg] [@has_local]
  | STORE_GLOBAL [@has_arg] [@has_name]
  | STORE_NAME [@has_arg] [@has_name]
  | STORE_SLICE
  | STORE_SUBSCR
  | SWAP [@has_arg]
  | TO_BOOL
  | UNARY_INVERT
  | UNARY_NEGATIVE
  | UNARY_NOT
  | UNPACK_EX [@has_arg]
  | UNPACK_SEQUENCE [@has_arg]
  | WITH_EXCEPT_START
  | YIELD_VALUE [@has_arg]
[@@deriving opcode, eq, ord]

let hash (x : t) = Hashtbl.hash x
let pp fmt x = Format.pp_print_string fmt (to_string x)

let python_version = "3.13.5"

(* Display tables for the pretty-printer (BINARY_OP / COMPARE_OP args). *)
let binary_op_repr = [| "+"; "&"; "//"; "<<"; "@"; "*"; "%"; "|"; "**"; ">>"; "-"; "/"; "^"; "+="; "&="; "//="; "<<="; "@="; "*="; "%="; "|="; "**="; ">>="; "-="; "/="; "^=" |]
let cmp_op_repr = [| "<"; "<="; "=="; "!="; ">"; ">=" |]
