xs = [3, 1, 2]
xs.append(4)
xs.extend([5, 6])
xs.insert(0, 0)
print(xs)
print(xs.pop(), xs.pop(0))
xs.remove(2)
print(xs, len(xs))
print(xs.index(3), xs.count(1))
xs.reverse()
print(xs)
xs.sort()
print(xs)
print([1, 2] + [3], [0] * 3)
