#!/usr/bin/env python3
"""Generate lib/opcode.ml and lib/opcode.mli from the host CPython's opcode tables.

Usage (run under the pinned interpreter):
    python3.13 tools/gen_opcodes.py --ml lib/opcode.ml --mli lib/opcode.mli

The generated variant is the union of all *real* opcodes (numeric value < 256)
of the supported CPython versions. Pseudo-opcodes (>= 256) never survive
assembly and are excluded. Opcode *names*, not numbers, are pytecode's wire
format: numbering is version-specific and irrelevant here.

The checked-in generated files are kept in sync via `dune build @gen`
(a diff rule fails on drift; `dune promote` updates them).
"""

import argparse
import dis
import opcode
import sys

EXPECTED = [(3, 13)]


def collect():
    if sys.version_info[:2] not in EXPECTED:
        sys.exit(
            "gen_opcodes.py: expected CPython %s, running %s"
            % (
                " or ".join("%d.%d" % v for v in EXPECTED),
                sys.version.split()[0],
            )
        )
    num2name = {num: name for name, num in opcode.opmap.items()}
    real = sorted(name for name, num in opcode.opmap.items() if num < 256)
    real_set = set(real)

    def prop(nums):
        return sorted(
            num2name[n] for n in nums if n in num2name and num2name[n] in real_set
        )

    props = [
        ("has_arg", prop(dis.hasarg), "[i.arg] is meaningful (HAVE_ARGUMENT)."),
        ("is_jump", prop(dis.hasjump), "the arg is a jump target (in pytecode: an absolute instruction index)."),
        ("has_const", prop(dis.hasconst), "the arg indexes [code.consts]."),
        ("has_name", prop(dis.hasname), "the arg indexes [code.names] (possibly with low flag bits, e.g. LOAD_GLOBAL/LOAD_ATTR)."),
        ("has_local", prop(dis.haslocal), "the arg indexes [code.localsplus]."),
        ("has_free", prop(dis.hasfree), "the arg indexes [code.localsplus] (cell/free slot)."),
        ("has_exc", prop(dis.hasexc), "intrinsic exception-related opcode (dis.hasexc)."),
    ]

    # Version-specific display tables used by the pretty-printer only.
    try:
        nb_ops = [sign for _name, sign in opcode._nb_ops]  # private; gen-time only
    except AttributeError:
        nb_ops = []
    cmp_ops = list(getattr(dis, "cmp_op", []))

    return real, props, nb_ops, cmp_ops


HEADER = """(* Generated by tools/gen_opcodes.py from CPython %s — DO NOT EDIT.
   Regenerate with: dune build @gen && dune promote *)
"""


def variant(real, props=None):
    """The variant declaration; with [props], each constructor carries the
    flag attributes ([@has_arg] etc.) the ppx_opcode deriver consumes."""
    lines = []
    for n in real:
        attrs = ""
        if props is not None:
            attrs = "".join(
                " [@%s]" % name for name, members, _doc in props if n in members
            )
        lines.append("  | %s%s" % (n, attrs))
    return "type t =\n" + "\n".join(lines) + "\n[@@deriving opcode]\n"


def gen_ml(real, props, nb_ops, cmp_ops, version):
    out = [HEADER % version]
    out.append(variant(real, props))

    out.append("let equal (a : t) (b : t) = a = b")
    out.append("let compare (a : t) (b : t) = Stdlib.compare a b")
    out.append("let hash (x : t) = Hashtbl.hash x")
    out.append("let pp fmt x = Format.pp_print_string fmt (to_string x)")
    out.append("")

    out.append('let python_version = "%s"' % version)
    out.append("")
    out.append("(* Display tables for the pretty-printer (BINARY_OP / COMPARE_OP args). *)")
    out.append(
        "let binary_op_repr = [| %s |]" % "; ".join('"%s"' % s for s in nb_ops)
    )
    out.append("let cmp_op_repr = [| %s |]" % "; ".join('"%s"' % s for s in cmp_ops))
    return "\n".join(out) + "\n"


def gen_mli(real, props, version):
    out = [HEADER % version]
    out.append("(** CPython opcodes, as a pure OCaml variant.")
    out.append("")
    out.append("    Union of all real opcodes (numeric value < 256) of the supported")
    out.append("    CPython versions (currently: %s). Pseudo-opcodes never survive"
               % version)
    out.append("    assembly and are excluded; specialized (adaptive) opcodes never")
    out.append("    appear in freshly compiled code.")
    out.append("")
    out.append("    [@@deriving opcode] declares [to_string], [of_string], [all]")
    out.append("    (declaration order, i.e. alphabetical), and one predicate per")
    out.append("    flag attribute:")
    for name, _members, doc in props:
        out.append("    - [%s]: %s" % (name, doc))
    out.append("*)")
    out.append("")
    out.append(variant(real))
    out.append("val equal : t -> t -> bool")
    out.append("val compare : t -> t -> int")
    out.append("val hash : t -> int")
    out.append("val pp : Format.formatter -> t -> unit")
    out.append("")
    out.append("val python_version : string")
    out.append("(** Full version of the CPython these tables were generated from. *)")
    out.append("")
    out.append("val binary_op_repr : string array")
    out.append('(** BINARY_OP arg -> operator string (e.g. ["+"]); display only. *)')
    out.append("")
    out.append("val cmp_op_repr : string array")
    out.append("(** COMPARE_OP (arg lsr 5) -> operator string; display only. *)")
    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ml", required=True)
    ap.add_argument("--mli", required=True)
    args = ap.parse_args()

    real, props, nb_ops, cmp_ops = collect()
    version = sys.version.split()[0]
    with open(args.ml, "w") as f:
        f.write(gen_ml(real, props, nb_ops, cmp_ops, version))
    with open(args.mli, "w") as f:
        f.write(gen_mli(real, props, version))


if __name__ == "__main__":
    main()
